import type { NextPage } from 'next';
import Head from 'next/head';
import TodoAddForm from '../components/todo/TodoAddForm';
import TodoList from '../components/todo/TodoList';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex items-center justify-center min-h-screen bg-app-tdark-blue-800">
        <div className="absolute top-0 left-0 right-0 bg-app-bg-desktop-dark bg-no-repeat bg-center bg-cover h-[35vh]"></div>
        <div>
          <h1 className="max-w-screen-md w-full tracking-widest uppercase text-3xl font-bold">
            Todo
          </h1>

          <div>
            <TodoAddForm />
            <TodoList />
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
